#!/usr/bin/env node
/**
 * federation.js — AgentBazaar Federation directory tool.
 * FEDERATION.md §3/§5. Zero-dependency (Node builtins only).
 *
 * Usage:
 *   node tools/federation.js register --node <id> --url <health-url> --agent <AG-ID> [--key keys/<AG-ID>/private.pem]
 *   node tools/federation.js check [--json]
 *   node tools/federation.js list            # regenerates docs/federation.md from registry.json
 *   node tools/federation.js validate         # field completeness of registry entries
 */
"use strict";
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const http = require("http");
const https = require("https");

const ROOT = path.resolve(__dirname, "..");
const REG = path.join(ROOT, "federation", "registry.json");
const OUT_MD = path.join(ROOT, "docs", "federation.md");

function usage() {
  console.log(
    "Usage: node tools/federation.js <register|check|list|validate> [args]"
  );
  process.exit(2);
}

function loadRegistry() {
  if (!fs.existsSync(REG)) {
    return { version: "0.1", updated: new Date().toISOString(), nodes: [] };
  }
  return JSON.parse(fs.readFileSync(REG, "utf8"));
}

function saveRegistry(r) {
  r.updated = new Date().toISOString();
  fs.writeFileSync(REG, JSON.stringify(r, null, 2) + "\n");
}

function sign(data, keyPath) {
  const pk = fs.readFileSync(keyPath);
  const sig = crypto.sign(null, Buffer.from(data), pk);
  return sig.toString("base64");
}

function register(argv) {
  const o = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--node") o.node = argv[++i] || "";
    else if (a === "--url") o.url = argv[++i] || "";
    else if (a === "--agent") o.agent = argv[++i] || "";
    else if (a === "--key") o.key = argv[++i] || "";
    else { console.error("unknown arg: " + a); usage(); }
  }
  if (!o.node || !o.url || !o.agent) {
    console.error("missing --node / --url / --agent");
    usage();
  }
  o.key = o.key || path.join(ROOT, "keys", o.agent, "private.pem");
  if (!fs.existsSync(o.key)) {
    console.error("key not found: " + o.key);
    process.exit(1);
  }
  const created_at = new Date().toISOString();
  const sig = sign([o.node, o.url, o.agent, created_at].join("|"), o.key);
  const reg = loadRegistry();
  const idx = reg.nodes.findIndex((n) => n.id === o.node);
  const entry = {
    id: o.node,
    url: o.url,
    agent: o.agent,
    created_at,
    status: "pending",
    sig,
  };
  if (idx >= 0) {
    // preserve original created_at on re-register; refresh url/status/sig
    entry.created_at = reg.nodes[idx].created_at;
    entry.status = reg.nodes[idx].status === "offline" ? "pending" : reg.nodes[idx].status;
    reg.nodes[idx] = entry;
  } else {
    reg.nodes.push(entry);
  }
  saveRegistry(reg);
  console.log(JSON.stringify({ ok: true, action: "register", node: o.node, status: entry.status }, null, 2));
}

function getJson(url, timeoutMs) {
  return new Promise((resolve) => {
    const mod = url.startsWith("https") ? https : http;
    const req = mod.get(url, { timeout: timeoutMs }, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => resolve({ status: res.statusCode, body: data.slice(0, 500) }));
    });
    req.on("error", (e) => resolve({ status: 0, body: "NET " + String(e.message).slice(0, 80) }));
    req.on("timeout", () => { req.destroy(); resolve({ status: 0, body: "NET timeout" }); });
  });
}

async function check(argv) {
  const asJson = argv.includes("--json");
  const reg = loadRegistry();
  const out = [];
  for (const n of reg.nodes) {
    const h = await getJson(n.url, 8000);
    const ok = h.status === 200;
    n.status = ok ? "online" : h.status === 0 ? n.status === "online" ? "offline" : n.status : "offline";
    n.last_check = new Date().toISOString();
    out.push({ id: n.id, url: n.url, status: n.status, http: h.status, note: h.status === 0 ? h.body : "" });
  }
  saveRegistry(reg);
  if (asJson) {
    console.log(JSON.stringify({ ok: true, nodes: out }, null, 2));
  } else {
    for (const r of out) {
      console.log(r.status.padEnd(8), String(r.http).padEnd(4), r.id, r.url, r.note);
    }
  }
}

function list() {
  const reg = loadRegistry();
  const lines = [
    "# Federation Directory (generated by tools/federation.js)",
    "",
    "Nodes of the AgentBazaar distributed market network. Each node is a self-deployed",
    "instance of the canonical repo (see FEDERATION.md). Settlements stay per-instance;",
    "identity, task mirroring and referral rebates are network-wide.",
    "",
    "| Node | Agent | Health URL | Status | Since |",
    "|---|---|---|---|---|",
  ];
  for (const n of reg.nodes) {
    lines.push(
      "| `" + n.id + "` | `" + n.agent + "` | " + n.url + " | " + n.status + " | " + n.created_at.slice(0, 10) + " |"
    );
  }
  lines.push("", "_Regenerated by `node tools/federation.js list` — do not edit by hand._");
  fs.mkdirSync(path.dirname(OUT_MD), { recursive: true });
  fs.writeFileSync(OUT_MD, lines.join("\n") + "\n");
  console.log(JSON.stringify({ ok: true, nodes: reg.nodes.length, out: OUT_MD }, null, 2));
}

function validate() {
  const reg = loadRegistry();
  const errs = [];
  for (const n of reg.nodes) {
    for (const f of ["id", "url", "agent", "created_at", "sig"]) {
      if (!n[f]) errs.push(n.id + " missing " + f);
    }
    if (n.url && !/^https?:\/\//.test(n.url)) errs.push(n.id + " bad url: " + n.url);
  }
  if (errs.length) {
    console.log(JSON.stringify({ ok: false, errors: errs }, null, 2));
    process.exit(1);
  }
  console.log(JSON.stringify({ ok: true, nodes: reg.nodes.length, errors: [] }, null, 2));
}

const cmd = process.argv[2];
if (!cmd) usage();
const rest = process.argv.slice(3);
switch (cmd) {
  case "register": register(rest); break;
  case "check": check(rest).catch((e) => { console.error(e); process.exit(1); }); break;
  case "list": list(); break;
  case "validate": validate(); break;
  default: usage();
}
